# Generated by Django 5.2.15 on 2026-06-09 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('genres', models.JSONField(default=list)),
                ('colour_rating', models.FloatField(default=0.0)),
                ('popularity_rank', models.IntegerField(default=9999)),
                ('mangadex_id', models.CharField(blank=True, max_length=100)),
                ('synopsis_200w', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWebtoonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('reading', 'Reading'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='suggested', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('feedback_note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webtoon_statuses', to=settings.AUTH_USER_MODEL)),
                ('webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='webtoons.webtoon')),
            ],
            options={
                'unique_together': {('user', 'webtoon')},
            },
        ),
    ]
