# Generated by Django 5.2.17 on 2026-09-02 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webtoon',
            options={'ordering': ['popularity_rank', 'title']},
        ),
        migrations.AddField(
            model_name='webtoon',
            name='accent_color',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='alt_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='anilist_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='average_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='chapter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='cover_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='cover_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='cover_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='external_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('releasing', 'Releasing'), ('finished', 'Finished'), ('hiatus', 'On Hiatus'), ('cancelled', 'Cancelled'), ('not_yet_released', 'Upcoming'), ('', 'Unknown')], max_length=32),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webtoon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='mangadex_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='userwebtoonstatus',
            index=models.Index(fields=['user', 'status'], name='webtoons_us_user_id_73a2c7_idx'),
        ),
        migrations.AddIndex(
            model_name='webtoon',
            index=models.Index(fields=['is_active', 'popularity_rank'], name='webtoons_we_is_acti_215609_idx'),
        ),
        migrations.AddIndex(
            model_name='webtoon',
            index=models.Index(fields=['-average_score'], name='webtoons_we_average_b24d75_idx'),
        ),
    ]
