# Generated by Django 5.2.15 on 2026-06-09 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppOperatingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phase', models.CharField(choices=[('onboarding', 'Onboarding'), ('scraping', 'Scraping'), ('embedding', 'Embedding'), ('feeding', 'Feeding'), ('feedback', 'Feedback'), ('expanding', 'Expanding')], max_length=30)),
                ('langgraph_run_id', models.CharField(blank=True, max_length=150)),
                ('langsmith_trace_url', models.URLField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1)),
                ('webtoons_suggested', models.JSONField(default=list)),
                ('all_skipped', models.BooleanField(default=False)),
                ('fallback_triggered', models.BooleanField(default=False)),
                ('scrape_expansion_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_cycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
