# Generated by Django 5.2.17 on 2026-09-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcycle',
            name='reasons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
